# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [15]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [19]:
# Create a 1-dimensional NumPy array using np.array()
np1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
np2 = np.array([[1,2,3,4],
                [5,6,7,8]])

# Create a 3-dimensional Numpy array using np.array()
np3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]
    ]])
np3

# Create a 5-dimensional Numpy array using np.array()
np5 = np.array([[[[[1,2,3]]]]])
np5.shape



(1, 1, 1, 1, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np1.shape
np1.dtype
np1.ndim
np1.size
type(np1)


(2, 3, 3)

In [ ]:
# Attributes of 2-dimensional array
np2.shape
np2.dtype
np2.ndim
np2.size
type(np2)

In [ ]:
# Attributes of 3-dimensional array
np3.shape
np3.dtype
np3.ndim
np3.size
type(np3)

In [29]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(np2)
df


,0,1,2,3
0,1,2,3,4
1,5,6,7,8


In [ ]:
# Create an array of shape (10, 2) with only ones
prac =np.ones((10,2))
prac

TypeError: 'tuple' object is not callable

In [36]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(11,size =(7,2))

array([[ 6,  4],
       [ 0,  7],
       [ 4,  3],
       [10,  7],
       [ 5,  6],
       [10,  0],
       [ 6, 10]])

In [50]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.96851804, 0.45442308, 0.74474488, 0.52554886, 0.36902793],
       [0.51353952, 0.88796856, 0.26223608, 0.11753021, 0.20717337],
       [0.20293097, 0.58945231, 0.27429062, 0.34284874, 0.9546544 ]])

In [54]:
# Set the random seed to 42
import random
random.seed(10)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(11, size = (4,6))

array([[ 8,  0,  9,  5,  1,  2],
       [ 2,  2,  6,  7,  3,  9],
       [ 7, 10,  2,  7,  2,  6],
       [ 6,  8,  5,  3,  1,  2]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

test = np.random.randint(11,size =(3,7))
test

# Find the unique numbers in the array you just created
np.unique(test)


array([0, 1, 2, 3, 4, 5, 7, 9])

In [83]:
test

array([[3, 2, 4, 2, 0, 9, 9],
       [0, 5, 3, 9, 4, 9, 1],
       [0, 1, 3, 7, 7, 4, 1]])

In [81]:
# Find the 0'th index of the latest array you created
test[0,0]
test[0:1,0:1]

array([[3]])

In [84]:
# Get the first 2 rows of latest array you created
test[0:2]

array([[3, 2, 4, 2, 0, 9, 9],
       [0, 5, 3, 9, 4, 9, 1]])

In [86]:
# Get the first 2 values of the first 2 rows of the latest array
test[0:2,0:2]

array([[3, 2],
       [0, 5]])

In [2]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
test_rand = np.random.randint(11,size= (3,5))

test1 =np.ones((3,5))

In [118]:
test1.dtype

dtype('float64')

In [3]:
# Add the two arrays together
new = test_rand + test1
new

array([[ 5.,  1.,  5., 10.,  8.],
       [ 9.,  3.,  9.,  5.,  5.],
       [ 8.,  4., 10.,  3.,  3.]])

In [4]:
# Create another array of ones of shape (5, 3)
test2 = np.ones((5,3))
test2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Try add the array of ones and the other most recent array together
test2 + new

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [18]:
import numpy as np

In [23]:
# Create another array of ones of shape (3, 5)
test2 = np.ones((3,5))

In [7]:
new.shape

(3, 5)

In [24]:
# Subtract the new array of ones from the other most recent array
new - test2 

array([[4., 0., 4., 9., 7.],
       [8., 2., 8., 4., 4.],
       [7., 3., 9., 2., 2.]])

In [ ]:
# Multiply the ones array with the latest array
new * test2

In [26]:
# Take the latest array to the power of 2 using '**'
new**2

array([[ 25.,   1.,  25., 100.,  64.],
       [ 81.,   9.,  81.,  25.,  25.],
       [ 64.,  16., 100.,   9.,   9.]])

In [28]:
# Do the same thing with np.square()
np.square(new)

array([[ 25.,   1.,  25., 100.,  64.],
       [ 81.,   9.,  81.,  25.,  25.],
       [ 64.,  16., 100.,   9.,   9.]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(new)

np.float64(5.866666666666666)

In [31]:
# Find the maximum of the latest array using np.max()
np.max(new)

np.float64(10.0)

In [32]:
# Find the minimum of the latest array using np.min()
np.min(new)

np.float64(1.0)

In [ ]:
# Find the standard deviation of the latest array
import statistics
np.std(new)



np.float64(2.8015868519267593)

In [34]:
# Find the variance of the latest array
np.var(new)

np.float64(7.848888888888889)

In [35]:
# Reshape the latest array to (3, 5, 1)
new.reshape(3,5,1)

array([[[ 5.],
        [ 1.],
        [ 5.],
        [10.],
        [ 8.]],

       [[ 9.],
        [ 3.],
        [ 9.],
        [ 5.],
        [ 5.]],

       [[ 8.],
        [ 4.],
        [10.],
        [ 3.],
        [ 3.]]])

In [36]:
# Transpose the latest array
new.T

array([[ 5.,  9.,  8.],
       [ 1.,  3.,  4.],
       [ 5.,  9., 10.],
       [10.,  5.,  3.],
       [ 8.,  5.,  3.]])

What does the transpose do?
Flips the axis of arrays.

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
test = np.random.randint(11, size=(3,3)) 
test2 = np.random.randint(11, size=(3,2))



array([[ 1,  9],
       [ 1,  0],
       [10,  5]])

In [39]:
# Perform a dot product on the two newest arrays you created
test.dot(test2)

array([[ 33, 100],
       [ 69,  39],
       [ 28,  77]])

In [41]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
test3 = np.random.randint(11, size=(4,3)) 
test4 = np.random.randint(11, size=(4,3))


In [42]:
# Perform a dot product on the two newest arrays you created
test3.dot(test4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [45]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
test3.T.dot(test4)

array([[132, 160, 164],
       [141, 157, 155],
       [107, 152, 145]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [56]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
test = np.random.randint(11,size=(3,3))
test2= np.random.randint(11, size=(3,3))

In [47]:
# Compare the two arrays with '>'
test > test2

array([[ True,  True, False],
       [False, False,  True],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [61]:
# Compare the two arrays with '>='
test>=test2

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [62]:
# Find which elements of the first array are greater than 7
test > 7

array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [63]:
# Which parts of each array are equal? (try using '==')
test == test2

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [65]:
# Sort one of the arrays you just created in ascending order
np.sort(test)

array([[ 1,  2, 10],
       [ 0,  2, 10],
       [ 1,  4,  7]])

In [66]:
# Sort the indexes of one of the arrays you just created
np.argsort(test)

array([[2, 0, 1],
       [2, 1, 0],
       [2, 1, 0]])

In [68]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(test)

np.int64(1)

In [69]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(test)

np.int64(5)

In [70]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(test, axis=1)

array([1, 0, 0])

In [71]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(test, axis=0)

array([1, 0, 0])

In [75]:
# Create an array of normally distributed random numbers
np.random.randn(3,4)

array([[ 0.19096052,  0.50750142, -0.51584071,  0.43418042],
       [ 0.02875601, -1.42491536, -1.1094051 ,  0.46032022],
       [ 1.21362261,  0.01167892,  1.95844076,  1.6416028 ]])

In [74]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even = np.arange(10,101, 10)
even

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.